### ISSUE TITLE
smd compile errors

### ISSUE THREAD

**Issue by KittenOnCatnip** [bonjorno7/SourceOps#75]
`Python: Traceback (most recent call last):
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\ops\export_auto.py", line 56, in invoke
    return self.execute(context)
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\ops\export_auto.py", line 76, in execute
    error = self.export(game, model)
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\ops\export_auto.py", line 89, in export
    error = source_model.export_meshes()
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\types\model_export\model.py", line 73, in export_meshes
    self.export_anim(self.armature, None, self.directory.joinpath('anims', 'idle.SMD'))
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\types\model_export\model.py", line 103, in export_anim
    self.export_smd(armature, [], action, path)
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\types\model_export\model.py", line 122, in export_smd
    smd.from_blender(armature, objects, action)
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 427, in from_blender
    self.lookup.from_blender(armature)
  File "C:\Users\flyin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 30, in from_blender
    for bone in armature.data.bones:
AttributeError: 'Mesh' object has no attribute 'bones'

location: <unknown location>:-1`

**Comment by KittenOnCatnip** [comment]
I had the armature setting selected on the export options. now it works thanks.
