### ISSUE TITLE
I have a problem when I try to export my model. 

### ISSUE THREAD

**Issue by dimaisaev1** [bonjorno7/SourceOps#86]
Python: Traceback (most recent call last):
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\ops\export_meshes.py", line 31, in invoke
    error = source_model.export_meshes()
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\types\model_export\model.py", line 76, in export_meshes
    self.export_anim(self.armature, None, self.directory.joinpath('anims', 'idle.SMD'))
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\types\model_export\model.py", line 106, in export_anim
    self.export_smd(armature, [], action, path)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\types\model_export\model.py", line 123, in export_smd
    smd.from_blender(armature, objects, action)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 427, in from_blender
    self.lookup.from_blender(armature)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 30, in from_blender
    for bone in armature.data.bones:
AttributeError: 'Mesh' object has no attribute 'bones'

**Comment by SethTooQuick** [comment]
Are you trying to make an animated prop or a static prop? If static, you have your ref geo in the armature input.
