### ISSUE TITLE
Can't export SMD in Blender 4.2

### ISSUE THREAD

**Issue by 14bit** [bonjorno7/SourceOps#94]
Blender removed the "Keep Custom Normals" checkbox on the Triangulate Modifier in 4.2, and that is now the [default behavior](https://projects.blender.org/blender/blender/issues/124836#issuecomment-1242350). This causes exports with SourceOps to fail, since from what I can tell it tries to set that checkbox that no longer exists:
```
Python: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\ops\export_meshes.py", line 31, in invoke
    error = source_model.export_meshes()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\types\model_export\model.py", line 88, in export_meshes
    self.export_mesh(self.armature, objects, path)
  File "C:\Username\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\types\model_export\model.py", line 113, in export_mesh
    self.export_smd(armature, objects, None, path)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\types\model_export\model.py", line 126, in export_smd
    smd.from_blender(armature, objects, action)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 435, in from_blender
    self.triangles.from_blender(self.lookup, armature, object)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceOps\addon\types\model_export\smd.py", line 358, in from_blender
    mod.keep_custom_normals = True
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TriangulateModifier' object has no attribute 'keep_custom_normals'
```

**Comment by bonjorno7** [comment]
I fixed this 20 days ago, but forgot to publish a release with that commit.
I'll have to get on that later this evening.

**Comment by bonjorno7** [comment]
Better late than never I suppose.
